trigger:
  branches:
    include:
      - main

pool:
  name: azureagent

variables:
- group: RenderSecrets

steps:
- checkout: self

# Use system-installed Python 3.12
- script: |
    python3.12 --version
    curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3.12
  displayName: 'Set up Python 3.12 with pip'

- script: |
    python3.12 -m pip install --upgrade pip
    python3.12 -m pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Package app'

- script: |
    curl -X POST "https://api.render.com/deploy/$(RENDER_SERVICE_ID)" \
         -H "Accept: application/json" \
         -H "Authorization: Bearer $(RENDER_API_KEY)"
  displayName: 'Deploy to Render'
