trigger:
  branches:
    include:
      - main  # Trigger on push to main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

# Install Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true

# Install dependencies
- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

# Archive app files into a zip for deployment
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-flask'  # Replace with your service connection name
    appName: 'my-web-akyl'                # Replace with your Azure Web App name
    package: '$(Build.ArtifactStagingDirectory)/*.zip'

