
trigger:
  branches:
    include:
      - main  # Trigger on push to main

pool:
  name: 'Default'  # This matches your .agent poolName

steps:
- checkout: self

# Ensure Python is installed on self-hosted agent
- script: |
    sudo apt update
    sudo apt install -y python3.12 python3.12-venv python3.12-distutils
    python3.12 --version
  displayName: 'Install Python 3.12 on agent'

# Add Python to PATH
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true

# Install dependencies
- script: |
    python3.12 -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Archive app files into a zip for deployment
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-flask'  # Must match exact service connection name in Azure DevOps
    appName: 'my-web-akyl'            # Your Azure Web App name
    package: '$(Build.ArtifactStagingDirectory)/*.zip'
